# Generated by Django 5.1.3 on 2024-11-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_alter_message_options_remove_message_updated_at'),
        ('users_app', '0003_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posted_comments', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='social_app.post'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendships_initiated', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendships_received', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='social_app.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_posts', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_messages', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_details', to='users_app.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_posts', to='users_app.user'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_requests_received', to='users_app.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_requests_sent', to='users_app.user')),
            ],
        ),
    ]
